export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const OPEN_CART_SECTION = "OPEN_CART_SECTION"
export const CLOSE_CART_SECTION = "CLOSE_CART_SECTION"
export const SET_DARKMODE_THEME = 'SET_DARKMODE_THEME'